server:
  port: 8282
spring:
  application:
    name: @artifactId@
qq-guild:
  base-url: https://api.sgroup.qq.com
  shard: 0, 1
  intents: 0, 12
  bot-app-id: 102176688
  bot-token: xce8CCaWN1ulr6EjdCxotFgxXS0mMNFt

# chatgpt 配置
chatgpt:
  # 代理配置
  proxy:
    # 开启：true false
    enable: true
    # 代理方式：http socks5
    type: socks5
    # 代理主机地址
    host: 127.0.0.1
    # 代理端口
    port: 7890
  # OpenAI key 可配置多个key
  apiKeys:
    - sk-EvI3oTGZOjo2cUHIpJqFUsYAsdnZzymKLeS909vjXtvUvpzX
  # OpenAI 请求地址
  apiHost: https://api.chatanywhere.tech